services:
  postgres-database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ezyevents
      POSTGRES_PASSWORD: qigfot-4Sobja-wixjut
      PGDATA: /var/lib/postgressql/data
    volumes:
      - ./postgres:/var/lib/postgressql/data
      - ./ezyevent.sql:/docker-entrypoint-initdb.d/ezyevent.sql
    restart: always
    networks:
      - ezy-network
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ezyevents
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
      - ./event-location-data.js:/docker-entrypoint-initdb.d/event-location-data.js:ro
    restart: always
    networks:
      - ezy-network

  ezy-event-api:
    image: johnyoat/ezyevent-api:1.1
    ports:
      - "8080:8080"
    links:
      - postgres-database
    networks:
      - ezy-network
    depends_on:
      - postgres-database
    restart: on-failure:20
  ezy-event-location-api:
    image: johnyoat/ezyevent-location-api:1.1
    ports:
      - "8081:8081"
    links:
      - "ezy-event-api"
    networks:
      - ezy-network 
    depends_on:
      - ezy-event-api
    restart: always
  ezy-event-web-app:
    image: johnyoat/ezyevent-web:1.2
    ports:
      - "80:80"
    networks:
      - ezy-network
    depends_on:
      - ezy-event-api  
networks:
  ezy-network:
    driver: bridge 